### ISSUE TITLE
Update Deploy User SSH Key for Github

### ISSUE THREAD

**Issue by Meowcenary** [galterlibrary/galter_dashing#45]
Deployments for this project are done using git from the server to pull changes in. The key that the deploy user is assigned to is being denied by Github and will need to be updated for future deployments.

After the config changes are done on Github immediately deploy both staging and production to make sure all environments are synced up.

**Comment by sharpattack** [comment]
Migrating dashing to a new server with newer OS. Not an issue on the new server.
